### ISSUE TITLE
May I have the dataset of O1_3p5B and O1_28B?

### ISSUE THREAD

**Issue by immelo** [malrabeiah/Sub6-Preds-mmWave#1]
I am trying to reproduce your work, but I can't find the datasets of O1_3p5B and O1_28B on the page of DeepMIMO. Can you give me the links of these two datasets?
Thank you very much!

**Comment by malrabeiah** [comment]
I am sorry for the late reply. You can check the DeepMIMO scenario web page: https://www.deepmimo.net/ray_tracing.html 
The scenarios are posted there.
